ROWS = 15
COLLUMNS = 20
TILE_SIZE = 50
SIDE_PANEL = 400
SCREEN_WIDTH = COLLUMNS * TILE_SIZE
SCREEN_HEIGHT = ROWS * TILE_SIZE
FPS = 60
HEALTH = 200
MONEY = 300
TOTAL_LEVELS = 50

#enemy constants
SPAWN_COOLDOWN = 420

#turret constants
ANIMATION_STEPS = 8
CLAW_ANIMATION_STEPS = 4
BUY_GUN_COST = 150
BUY_CLAW_COST = 200
BUY_CASH_COST = 300
ANIMATION_DELAY = 5
TURRET_LEVELS = 4
KILL_REWARD = 1
LEVEL_COMPLETE_REWARD = 100